'use strict';
const $=s=>document.querySelector(s);let weird=0,events=0,started=Date.now(),toastTimer,ambientTimer;const timers=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const messages=['Mildly suspicious. Further observation required.','The page has developed opinions. None were requested.','This is no longer covered by the instruction manual.','The website is now supervising you.','Reality has been placed in the incident log.','Maximum weirdness. Surprisingly stable.'];
function later(fn,ms){const id=setTimeout(()=>{timers.delete(id);fn();},ms);timers.add(id);return id;}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function log(text){const row=document.createElement('p'),time=document.createElement('time'),msg=document.createElement('span');const secs=Math.floor((Date.now()-started)/1000);time.textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0');msg.textContent=text;row.append(time,msg);$('#log').prepend(row);while($('#log').children.length>20)$('#log').lastChild.remove();}
function escalate(text,amount=9){events++;weird=Math.min(100,weird+amount);$('#level').textContent=String(weird).padStart(2,'0')+'%';$('#fill').style.width=weird+'%';$('#diagnosis').textContent=messages[Math.min(5,Math.floor(weird/20))];$('#status').textContent=weird<25?'PROBABLY FINE':weird<60?'SLIGHTLY OFF':'DEFINITELY WEIRD';document.body.classList.toggle('wobbly',weird>35&&!reduced);log(text);if(weird===100&&!$('#floaters').children.length){floaters();toast('Congratulations. You are now part of the problem.');}}
function floaters(){for(let i=0;i<8&&$('#floaters').children.length<16;i++){const s=document.createElement('span');s.className='floater';s.textContent=['?','↗','*','!'][i%4];s.style.left=(5+i*12)+'%';s.style.top=(10+Math.random()*70)+'%';s.style.animationDelay=-i*.4+'s';$('#floaters').append(s);}}
const titles=['What is<br>with this<br><span class="last-word">page<span class="question">?</span></span>','Who let<br>you in<br><span class="last-word">here<span class="question">?</span></span>','It was<br>like this<br><span class="last-word">already.</span>','Please<br>stop being<br><span class="last-word">normal.</span>'];let titleIndex=0;
function titleChange(){titleIndex=(titleIndex+1)%titles.length;$('#headline').innerHTML=titles[titleIndex];escalate('Headline changed its story.');toast('The title denies ever saying anything else.');}
$('#headline').onclick=titleChange;
function accessibleClick(el){el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});}accessibleClick($('#headline'));accessibleClick($('#eyeball'));
document.addEventListener('pointermove',e=>{if(reduced)return;const r=$('.eye').getBoundingClientRect();const x=Math.max(-13,Math.min(13,(e.clientX-r.x-r.width/2)/25)),y=Math.max(-10,Math.min(10,(e.clientY-r.y-r.height/2)/25));$('.iris').style.transform=`translate(${x}px,${y}px)`;});
$('#eyeball').onclick=()=>{escalate('Visitor made eye contact. Eye took it personally.',12);toast(['I saw that.','Blinking is a sign of weakness.','You have something on your cursor.'][events%3]);$('.pupil').style.width='12px';later(()=>$('.pupil').style.width='',1300);};
let observations=0;$('#card-one').onclick=()=>{observations++;escalate('The page issued another unverified statement.');$('#card-one h2').innerHTML=['Everything<br>is <em>fine.</em>','Everything<br>is <em>probably fine.</em>','Everything<br>is <em>in denial.</em>','Nothing<br>is <em>my fault.</em>'][observations%4];document.body.classList.toggle('inverted');$('meta[name="theme-color"]').content=document.body.classList.contains('inverted')?'#22231f':'#f3f0e8';toast('A small adjustment to the laws of light.');};
let pokes=0;$('#card-two').onclick=()=>{pokes++;escalate('Visitor ignored perfectly clear instructions.',12);$('#card-two').classList.toggle('tilt');$('#card-two h2').innerHTML=pokes%2?'You had<br><em>one instruction.</em>':"Please don't<br><em>poke around.</em>";toast(pokes%2?'This has been noted in your permanent temporary record.':'You did it again. Impressive commitment.');if(pokes%3===0){$('#description').textContent='It is now behaving exactly as badly as you are.';floaters();}};
$('#card-three').onclick=()=>{escalate('Emergency exit led back into the emergency.');$('#door').showModal();};$('#close-door').onclick=$('#return').onclick=()=>{$('#door').close();toast('Welcome back. You never left.');};
$('#footer-note').onclick=()=>{escalate('Visitor questioned the structural integrity of the footer.');$('footer').classList.toggle('tilt');toast('Please be careful. This footer supports the whole internet.');};
function ambient(){clearTimeout(ambientTimer);ambientTimer=setTimeout(()=>{if(!document.hidden&&!$('#door').open){escalate('Page became uncomfortable with the silence.',4);$('#serial').textContent=['STILL HERE?','THE PAGE IS ALSO WAITING','THIS IS A VERY LONG EYE CONTACT'][events%3];toast('The page would like to know what you are waiting for.');}ambient();},24000);}
let keyBuffer='';document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.key.length!==1)return;keyBuffer=(keyBuffer+e.key.toLowerCase()).slice(-5);if(keyBuffer==='weird'){escalate('Secret word accepted. Normality revoked.',25);floaters();toast('Ah. You speak fluent weird.');}});
$('#calm').onclick=()=>{for(const t of timers)clearTimeout(t);timers.clear();clearTimeout(toastTimer);weird=0;events=0;pokes=0;observations=0;titleIndex=0;started=Date.now();keyBuffer='';document.body.classList.remove('inverted','wobbly');$('#headline').innerHTML=titles[0];$('#card-one h2').innerHTML='Everything<br>is <em>fine.</em>';$('#card-two h2').innerHTML="Please don't<br><em>poke around.</em>";$('#card-two').classList.remove('tilt');$('footer').classList.remove('tilt');$('#floaters').replaceChildren();$('#log').replaceChildren();$('.pupil').style.width='';$('#level').textContent='00%';$('#fill').style.width='0%';$('#status').textContent='PROBABLY FINE';$('#diagnosis').textContent=messages[0];$('#description').innerHTML='It was behaving normally<br>before you got here.';$('#serial').textContent='PLEASE ACT NATURAL';$('meta[name="theme-color"]').content='#f3f0e8';$('#door').close();log('Order restored. The page is making no promises.');toast('Everything is normal again. For now.');ambient();};
ambient();
